new_run
Signed-off-by: Tarun Kumar <takumar@redhat.com>

diff --git a/.github/workflows/code_quality.yaml b/.github/workflows/code_quality.yaml
--- a/.github/workflows/code_quality.yaml
+++ b/.github/workflows/code_quality.yaml
@@ -39,3 +39,22 @@ jobs:
           pattern: "*.sh"
           exclude: "./.git/*"
           check_all_files_with_shebangs: "false"
+  robocop:
+     name: robocop
+     runs-on: ubuntu-latest
+      # continue even if Robocop returns issues and fails step
+      continue-on-error: true
+      steps:
+        -   name: Checkout repository
+            uses: actions/checkout@v3
+        -   name: Install dependencies
+            run: |
+                 python -m pip install --upgrade pip
+                 pip install robotframework-robocop
+        -   name: Run robocop
+            run: python -m robocop --verbose --reports sarif . || true
+        -   name: Upload SARIF file
+            uses: github/codeql-action/upload-sarif@v2
+            with:
+                sarif_file: .sarif.json
+                category: robocop
